# Generated by Django 5.2.9 on 2026-01-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptopayment',
            name='crypto_currency',
            field=models.CharField(default='USDT', max_length=10),
        ),
    ]
